package com.tubaoapi.model.so;

import java.math.BigDecimal;
import java.util.Date;

public class MaterialReqBillSO extends BaseSO<String>{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FCREATORID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String fcreatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FCREATETIME
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private Date fcreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FLASTUPDATEUSERID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String flastupdateuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FLASTUPDATETIME
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private Date flastupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FCONTROLUNITID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String fcontrolunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FNUMBER
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private Object fnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FBIZDATE
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private Date fbizdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FHANDLERID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String fhandlerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FDESCRIPTION
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private Object fdescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FHASEFFECTED
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private Long fhaseffected;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FAUDITORID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String fauditorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FSOURCEBILLID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private Object fsourcebillid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FSOURCEFUNCTION
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private Object fsourcefunction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FAUDITTIME
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private Date faudittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FBASESTATUS
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private Long fbasestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FBIZTYPEID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String fbiztypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FSOURCEBILLTYPEID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String fsourcebilltypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FBILLTYPEID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String fbilltypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FYEAR
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private Long fyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FPERIOD
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private Long fperiod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FSTORAGEORGUNITID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String fstorageorgunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FADMINORGUNITID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String fadminorgunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FSTOCKERID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String fstockerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FVOUCHERID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String fvoucherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FTOTALQTY
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private BigDecimal ftotalqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FTOTALAMOUNT
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private BigDecimal ftotalamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FFIVOUCHERED
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private Long ffivouchered;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FTOTALSTANDARDCOST
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private BigDecimal ftotalstandardcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FTOTALACTUALCOST
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private BigDecimal ftotalactualcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FISREVERSED
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private Long fisreversed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FTRANSACTIONTYPEID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String ftransactiontypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FISINITBILL
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private Long fisinitbill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FMODIFIERID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String fmodifierid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FMODIFICATIONTIME
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private Date fmodificationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FCOSTCENTERORGUNITID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String fcostcenterorgunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FPURCHASETYPE
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private Long fpurchasetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FSUPPLIERID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String fsupplierid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FISBACKFLUSH
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private Long fisbackflush;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FBACKFLUSHBILLTYPEID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String fbackflushbilltypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FBACKFLUSHBILLID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String fbackflushbillid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FMONTH
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private Long fmonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FDAY
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private Long fday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FSUPPLYSTOREORGUNITID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String fsupplystoreorgunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FSUPPLYCOMPANYORGUNITID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String fsupplycompanyorgunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.FDEMANDCOMPANYORGUNITID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String fdemandcompanyorgunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.CFOPPOSITEACCOUNTI
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String cfoppositeaccounti;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.CFINNERCUSTOMERID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String cfinnercustomerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILL.CFACCOUNTID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    private String cfaccountid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FID
     *
     * @return the value of T_IM_MATERIALREQBILL.FID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FID
     *
     * @param fid the value for T_IM_MATERIALREQBILL.FID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFid(String fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FCREATORID
     *
     * @return the value of T_IM_MATERIALREQBILL.FCREATORID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFcreatorid() {
        return fcreatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FCREATORID
     *
     * @param fcreatorid the value for T_IM_MATERIALREQBILL.FCREATORID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFcreatorid(String fcreatorid) {
        this.fcreatorid = fcreatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FCREATETIME
     *
     * @return the value of T_IM_MATERIALREQBILL.FCREATETIME
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public Date getFcreatetime() {
        return fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FCREATETIME
     *
     * @param fcreatetime the value for T_IM_MATERIALREQBILL.FCREATETIME
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFcreatetime(Date fcreatetime) {
        this.fcreatetime = fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FLASTUPDATEUSERID
     *
     * @return the value of T_IM_MATERIALREQBILL.FLASTUPDATEUSERID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFlastupdateuserid() {
        return flastupdateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FLASTUPDATEUSERID
     *
     * @param flastupdateuserid the value for T_IM_MATERIALREQBILL.FLASTUPDATEUSERID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFlastupdateuserid(String flastupdateuserid) {
        this.flastupdateuserid = flastupdateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FLASTUPDATETIME
     *
     * @return the value of T_IM_MATERIALREQBILL.FLASTUPDATETIME
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public Date getFlastupdatetime() {
        return flastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FLASTUPDATETIME
     *
     * @param flastupdatetime the value for T_IM_MATERIALREQBILL.FLASTUPDATETIME
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFlastupdatetime(Date flastupdatetime) {
        this.flastupdatetime = flastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FCONTROLUNITID
     *
     * @return the value of T_IM_MATERIALREQBILL.FCONTROLUNITID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFcontrolunitid() {
        return fcontrolunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FCONTROLUNITID
     *
     * @param fcontrolunitid the value for T_IM_MATERIALREQBILL.FCONTROLUNITID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFcontrolunitid(String fcontrolunitid) {
        this.fcontrolunitid = fcontrolunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FNUMBER
     *
     * @return the value of T_IM_MATERIALREQBILL.FNUMBER
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public Object getFnumber() {
        return fnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FNUMBER
     *
     * @param fnumber the value for T_IM_MATERIALREQBILL.FNUMBER
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFnumber(Object fnumber) {
        this.fnumber = fnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FBIZDATE
     *
     * @return the value of T_IM_MATERIALREQBILL.FBIZDATE
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public Date getFbizdate() {
        return fbizdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FBIZDATE
     *
     * @param fbizdate the value for T_IM_MATERIALREQBILL.FBIZDATE
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFbizdate(Date fbizdate) {
        this.fbizdate = fbizdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FHANDLERID
     *
     * @return the value of T_IM_MATERIALREQBILL.FHANDLERID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFhandlerid() {
        return fhandlerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FHANDLERID
     *
     * @param fhandlerid the value for T_IM_MATERIALREQBILL.FHANDLERID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFhandlerid(String fhandlerid) {
        this.fhandlerid = fhandlerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FDESCRIPTION
     *
     * @return the value of T_IM_MATERIALREQBILL.FDESCRIPTION
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public Object getFdescription() {
        return fdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FDESCRIPTION
     *
     * @param fdescription the value for T_IM_MATERIALREQBILL.FDESCRIPTION
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFdescription(Object fdescription) {
        this.fdescription = fdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FHASEFFECTED
     *
     * @return the value of T_IM_MATERIALREQBILL.FHASEFFECTED
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public Long getFhaseffected() {
        return fhaseffected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FHASEFFECTED
     *
     * @param fhaseffected the value for T_IM_MATERIALREQBILL.FHASEFFECTED
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFhaseffected(Long fhaseffected) {
        this.fhaseffected = fhaseffected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FAUDITORID
     *
     * @return the value of T_IM_MATERIALREQBILL.FAUDITORID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFauditorid() {
        return fauditorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FAUDITORID
     *
     * @param fauditorid the value for T_IM_MATERIALREQBILL.FAUDITORID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFauditorid(String fauditorid) {
        this.fauditorid = fauditorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FSOURCEBILLID
     *
     * @return the value of T_IM_MATERIALREQBILL.FSOURCEBILLID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public Object getFsourcebillid() {
        return fsourcebillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FSOURCEBILLID
     *
     * @param fsourcebillid the value for T_IM_MATERIALREQBILL.FSOURCEBILLID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFsourcebillid(Object fsourcebillid) {
        this.fsourcebillid = fsourcebillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FSOURCEFUNCTION
     *
     * @return the value of T_IM_MATERIALREQBILL.FSOURCEFUNCTION
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public Object getFsourcefunction() {
        return fsourcefunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FSOURCEFUNCTION
     *
     * @param fsourcefunction the value for T_IM_MATERIALREQBILL.FSOURCEFUNCTION
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFsourcefunction(Object fsourcefunction) {
        this.fsourcefunction = fsourcefunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FAUDITTIME
     *
     * @return the value of T_IM_MATERIALREQBILL.FAUDITTIME
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public Date getFaudittime() {
        return faudittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FAUDITTIME
     *
     * @param faudittime the value for T_IM_MATERIALREQBILL.FAUDITTIME
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFaudittime(Date faudittime) {
        this.faudittime = faudittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FBASESTATUS
     *
     * @return the value of T_IM_MATERIALREQBILL.FBASESTATUS
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public Long getFbasestatus() {
        return fbasestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FBASESTATUS
     *
     * @param fbasestatus the value for T_IM_MATERIALREQBILL.FBASESTATUS
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFbasestatus(Long fbasestatus) {
        this.fbasestatus = fbasestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FBIZTYPEID
     *
     * @return the value of T_IM_MATERIALREQBILL.FBIZTYPEID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFbiztypeid() {
        return fbiztypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FBIZTYPEID
     *
     * @param fbiztypeid the value for T_IM_MATERIALREQBILL.FBIZTYPEID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFbiztypeid(String fbiztypeid) {
        this.fbiztypeid = fbiztypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FSOURCEBILLTYPEID
     *
     * @return the value of T_IM_MATERIALREQBILL.FSOURCEBILLTYPEID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFsourcebilltypeid() {
        return fsourcebilltypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FSOURCEBILLTYPEID
     *
     * @param fsourcebilltypeid the value for T_IM_MATERIALREQBILL.FSOURCEBILLTYPEID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFsourcebilltypeid(String fsourcebilltypeid) {
        this.fsourcebilltypeid = fsourcebilltypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FBILLTYPEID
     *
     * @return the value of T_IM_MATERIALREQBILL.FBILLTYPEID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFbilltypeid() {
        return fbilltypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FBILLTYPEID
     *
     * @param fbilltypeid the value for T_IM_MATERIALREQBILL.FBILLTYPEID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFbilltypeid(String fbilltypeid) {
        this.fbilltypeid = fbilltypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FYEAR
     *
     * @return the value of T_IM_MATERIALREQBILL.FYEAR
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public Long getFyear() {
        return fyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FYEAR
     *
     * @param fyear the value for T_IM_MATERIALREQBILL.FYEAR
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFyear(Long fyear) {
        this.fyear = fyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FPERIOD
     *
     * @return the value of T_IM_MATERIALREQBILL.FPERIOD
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public Long getFperiod() {
        return fperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FPERIOD
     *
     * @param fperiod the value for T_IM_MATERIALREQBILL.FPERIOD
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFperiod(Long fperiod) {
        this.fperiod = fperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FSTORAGEORGUNITID
     *
     * @return the value of T_IM_MATERIALREQBILL.FSTORAGEORGUNITID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFstorageorgunitid() {
        return fstorageorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FSTORAGEORGUNITID
     *
     * @param fstorageorgunitid the value for T_IM_MATERIALREQBILL.FSTORAGEORGUNITID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFstorageorgunitid(String fstorageorgunitid) {
        this.fstorageorgunitid = fstorageorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FADMINORGUNITID
     *
     * @return the value of T_IM_MATERIALREQBILL.FADMINORGUNITID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFadminorgunitid() {
        return fadminorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FADMINORGUNITID
     *
     * @param fadminorgunitid the value for T_IM_MATERIALREQBILL.FADMINORGUNITID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFadminorgunitid(String fadminorgunitid) {
        this.fadminorgunitid = fadminorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FSTOCKERID
     *
     * @return the value of T_IM_MATERIALREQBILL.FSTOCKERID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFstockerid() {
        return fstockerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FSTOCKERID
     *
     * @param fstockerid the value for T_IM_MATERIALREQBILL.FSTOCKERID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFstockerid(String fstockerid) {
        this.fstockerid = fstockerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FVOUCHERID
     *
     * @return the value of T_IM_MATERIALREQBILL.FVOUCHERID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFvoucherid() {
        return fvoucherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FVOUCHERID
     *
     * @param fvoucherid the value for T_IM_MATERIALREQBILL.FVOUCHERID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFvoucherid(String fvoucherid) {
        this.fvoucherid = fvoucherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FTOTALQTY
     *
     * @return the value of T_IM_MATERIALREQBILL.FTOTALQTY
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public BigDecimal getFtotalqty() {
        return ftotalqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FTOTALQTY
     *
     * @param ftotalqty the value for T_IM_MATERIALREQBILL.FTOTALQTY
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFtotalqty(BigDecimal ftotalqty) {
        this.ftotalqty = ftotalqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FTOTALAMOUNT
     *
     * @return the value of T_IM_MATERIALREQBILL.FTOTALAMOUNT
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public BigDecimal getFtotalamount() {
        return ftotalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FTOTALAMOUNT
     *
     * @param ftotalamount the value for T_IM_MATERIALREQBILL.FTOTALAMOUNT
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFtotalamount(BigDecimal ftotalamount) {
        this.ftotalamount = ftotalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FFIVOUCHERED
     *
     * @return the value of T_IM_MATERIALREQBILL.FFIVOUCHERED
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public Long getFfivouchered() {
        return ffivouchered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FFIVOUCHERED
     *
     * @param ffivouchered the value for T_IM_MATERIALREQBILL.FFIVOUCHERED
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFfivouchered(Long ffivouchered) {
        this.ffivouchered = ffivouchered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FTOTALSTANDARDCOST
     *
     * @return the value of T_IM_MATERIALREQBILL.FTOTALSTANDARDCOST
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public BigDecimal getFtotalstandardcost() {
        return ftotalstandardcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FTOTALSTANDARDCOST
     *
     * @param ftotalstandardcost the value for T_IM_MATERIALREQBILL.FTOTALSTANDARDCOST
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFtotalstandardcost(BigDecimal ftotalstandardcost) {
        this.ftotalstandardcost = ftotalstandardcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FTOTALACTUALCOST
     *
     * @return the value of T_IM_MATERIALREQBILL.FTOTALACTUALCOST
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public BigDecimal getFtotalactualcost() {
        return ftotalactualcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FTOTALACTUALCOST
     *
     * @param ftotalactualcost the value for T_IM_MATERIALREQBILL.FTOTALACTUALCOST
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFtotalactualcost(BigDecimal ftotalactualcost) {
        this.ftotalactualcost = ftotalactualcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FISREVERSED
     *
     * @return the value of T_IM_MATERIALREQBILL.FISREVERSED
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public Long getFisreversed() {
        return fisreversed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FISREVERSED
     *
     * @param fisreversed the value for T_IM_MATERIALREQBILL.FISREVERSED
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFisreversed(Long fisreversed) {
        this.fisreversed = fisreversed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FTRANSACTIONTYPEID
     *
     * @return the value of T_IM_MATERIALREQBILL.FTRANSACTIONTYPEID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFtransactiontypeid() {
        return ftransactiontypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FTRANSACTIONTYPEID
     *
     * @param ftransactiontypeid the value for T_IM_MATERIALREQBILL.FTRANSACTIONTYPEID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFtransactiontypeid(String ftransactiontypeid) {
        this.ftransactiontypeid = ftransactiontypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FISINITBILL
     *
     * @return the value of T_IM_MATERIALREQBILL.FISINITBILL
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public Long getFisinitbill() {
        return fisinitbill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FISINITBILL
     *
     * @param fisinitbill the value for T_IM_MATERIALREQBILL.FISINITBILL
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFisinitbill(Long fisinitbill) {
        this.fisinitbill = fisinitbill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FMODIFIERID
     *
     * @return the value of T_IM_MATERIALREQBILL.FMODIFIERID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFmodifierid() {
        return fmodifierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FMODIFIERID
     *
     * @param fmodifierid the value for T_IM_MATERIALREQBILL.FMODIFIERID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFmodifierid(String fmodifierid) {
        this.fmodifierid = fmodifierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FMODIFICATIONTIME
     *
     * @return the value of T_IM_MATERIALREQBILL.FMODIFICATIONTIME
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public Date getFmodificationtime() {
        return fmodificationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FMODIFICATIONTIME
     *
     * @param fmodificationtime the value for T_IM_MATERIALREQBILL.FMODIFICATIONTIME
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFmodificationtime(Date fmodificationtime) {
        this.fmodificationtime = fmodificationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FCOSTCENTERORGUNITID
     *
     * @return the value of T_IM_MATERIALREQBILL.FCOSTCENTERORGUNITID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFcostcenterorgunitid() {
        return fcostcenterorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FCOSTCENTERORGUNITID
     *
     * @param fcostcenterorgunitid the value for T_IM_MATERIALREQBILL.FCOSTCENTERORGUNITID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFcostcenterorgunitid(String fcostcenterorgunitid) {
        this.fcostcenterorgunitid = fcostcenterorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FPURCHASETYPE
     *
     * @return the value of T_IM_MATERIALREQBILL.FPURCHASETYPE
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public Long getFpurchasetype() {
        return fpurchasetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FPURCHASETYPE
     *
     * @param fpurchasetype the value for T_IM_MATERIALREQBILL.FPURCHASETYPE
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFpurchasetype(Long fpurchasetype) {
        this.fpurchasetype = fpurchasetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FSUPPLIERID
     *
     * @return the value of T_IM_MATERIALREQBILL.FSUPPLIERID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFsupplierid() {
        return fsupplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FSUPPLIERID
     *
     * @param fsupplierid the value for T_IM_MATERIALREQBILL.FSUPPLIERID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFsupplierid(String fsupplierid) {
        this.fsupplierid = fsupplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FISBACKFLUSH
     *
     * @return the value of T_IM_MATERIALREQBILL.FISBACKFLUSH
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public Long getFisbackflush() {
        return fisbackflush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FISBACKFLUSH
     *
     * @param fisbackflush the value for T_IM_MATERIALREQBILL.FISBACKFLUSH
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFisbackflush(Long fisbackflush) {
        this.fisbackflush = fisbackflush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FBACKFLUSHBILLTYPEID
     *
     * @return the value of T_IM_MATERIALREQBILL.FBACKFLUSHBILLTYPEID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFbackflushbilltypeid() {
        return fbackflushbilltypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FBACKFLUSHBILLTYPEID
     *
     * @param fbackflushbilltypeid the value for T_IM_MATERIALREQBILL.FBACKFLUSHBILLTYPEID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFbackflushbilltypeid(String fbackflushbilltypeid) {
        this.fbackflushbilltypeid = fbackflushbilltypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FBACKFLUSHBILLID
     *
     * @return the value of T_IM_MATERIALREQBILL.FBACKFLUSHBILLID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFbackflushbillid() {
        return fbackflushbillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FBACKFLUSHBILLID
     *
     * @param fbackflushbillid the value for T_IM_MATERIALREQBILL.FBACKFLUSHBILLID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFbackflushbillid(String fbackflushbillid) {
        this.fbackflushbillid = fbackflushbillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FMONTH
     *
     * @return the value of T_IM_MATERIALREQBILL.FMONTH
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public Long getFmonth() {
        return fmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FMONTH
     *
     * @param fmonth the value for T_IM_MATERIALREQBILL.FMONTH
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFmonth(Long fmonth) {
        this.fmonth = fmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FDAY
     *
     * @return the value of T_IM_MATERIALREQBILL.FDAY
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public Long getFday() {
        return fday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FDAY
     *
     * @param fday the value for T_IM_MATERIALREQBILL.FDAY
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFday(Long fday) {
        this.fday = fday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FSUPPLYSTOREORGUNITID
     *
     * @return the value of T_IM_MATERIALREQBILL.FSUPPLYSTOREORGUNITID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFsupplystoreorgunitid() {
        return fsupplystoreorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FSUPPLYSTOREORGUNITID
     *
     * @param fsupplystoreorgunitid the value for T_IM_MATERIALREQBILL.FSUPPLYSTOREORGUNITID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFsupplystoreorgunitid(String fsupplystoreorgunitid) {
        this.fsupplystoreorgunitid = fsupplystoreorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FSUPPLYCOMPANYORGUNITID
     *
     * @return the value of T_IM_MATERIALREQBILL.FSUPPLYCOMPANYORGUNITID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFsupplycompanyorgunitid() {
        return fsupplycompanyorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FSUPPLYCOMPANYORGUNITID
     *
     * @param fsupplycompanyorgunitid the value for T_IM_MATERIALREQBILL.FSUPPLYCOMPANYORGUNITID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFsupplycompanyorgunitid(String fsupplycompanyorgunitid) {
        this.fsupplycompanyorgunitid = fsupplycompanyorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.FDEMANDCOMPANYORGUNITID
     *
     * @return the value of T_IM_MATERIALREQBILL.FDEMANDCOMPANYORGUNITID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getFdemandcompanyorgunitid() {
        return fdemandcompanyorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.FDEMANDCOMPANYORGUNITID
     *
     * @param fdemandcompanyorgunitid the value for T_IM_MATERIALREQBILL.FDEMANDCOMPANYORGUNITID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setFdemandcompanyorgunitid(String fdemandcompanyorgunitid) {
        this.fdemandcompanyorgunitid = fdemandcompanyorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.CFOPPOSITEACCOUNTI
     *
     * @return the value of T_IM_MATERIALREQBILL.CFOPPOSITEACCOUNTI
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getCfoppositeaccounti() {
        return cfoppositeaccounti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.CFOPPOSITEACCOUNTI
     *
     * @param cfoppositeaccounti the value for T_IM_MATERIALREQBILL.CFOPPOSITEACCOUNTI
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setCfoppositeaccounti(String cfoppositeaccounti) {
        this.cfoppositeaccounti = cfoppositeaccounti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.CFINNERCUSTOMERID
     *
     * @return the value of T_IM_MATERIALREQBILL.CFINNERCUSTOMERID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getCfinnercustomerid() {
        return cfinnercustomerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.CFINNERCUSTOMERID
     *
     * @param cfinnercustomerid the value for T_IM_MATERIALREQBILL.CFINNERCUSTOMERID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setCfinnercustomerid(String cfinnercustomerid) {
        this.cfinnercustomerid = cfinnercustomerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILL.CFACCOUNTID
     *
     * @return the value of T_IM_MATERIALREQBILL.CFACCOUNTID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public String getCfaccountid() {
        return cfaccountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILL.CFACCOUNTID
     *
     * @param cfaccountid the value for T_IM_MATERIALREQBILL.CFACCOUNTID
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    public void setCfaccountid(String cfaccountid) {
        this.cfaccountid = cfaccountid;
    }
}