package com.tubaoapi.dao;

import com.tubaoapi.model.ManufactureRecBill;

public interface ManufactureRecBillDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_IM_MANUFACTURERECBILL
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    int insert(ManufactureRecBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_IM_MANUFACTURERECBILL
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    int insertSelective(ManufactureRecBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_IM_MANUFACTURERECBILL
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    int updateByPrimaryKeySelective(ManufactureRecBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_IM_MANUFACTURERECBILL
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    int updateByPrimaryKey(ManufactureRecBill record);
}