package com.tubaoapi.dao;

import com.tubaoapi.model.ManufactureRecBillEntry;

public interface ManufactureRecBillEntryDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_IM_MANUFACTURERECBILLENTRY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    int insert(ManufactureRecBillEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_IM_MANUFACTURERECBILLENTRY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    int insertSelective(ManufactureRecBillEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_IM_MANUFACTURERECBILLENTRY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    int updateByPrimaryKeySelective(ManufactureRecBillEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_IM_MANUFACTURERECBILLENTRY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    int updateByPrimaryKey(ManufactureRecBillEntry record);
}