package com.tubaoapi.dao;

import com.tubaoapi.model.MaterialReqBillEntry;

public interface MaterialReqBillEntryDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_IM_MATERIALREQBILLENTRY
     *
     * @mbggenerated Fri Jun 08 08:43:28 CST 2018
     */
    int insert(MaterialReqBillEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_IM_MATERIALREQBILLENTRY
     *
     * @mbggenerated Fri Jun 08 08:43:28 CST 2018
     */
    int insertSelective(MaterialReqBillEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_IM_MATERIALREQBILLENTRY
     *
     * @mbggenerated Fri Jun 08 08:43:28 CST 2018
     */
    int updateByPrimaryKeySelective(MaterialReqBillEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_IM_MATERIALREQBILLENTRY
     *
     * @mbggenerated Fri Jun 08 08:43:28 CST 2018
     */
    int updateByPrimaryKey(MaterialReqBillEntry record);
}