package com.tubaoapi.dao;

import com.tubaoapi.model.MaterialReqBillPriceInfo;

public interface MaterialReqBillPriceInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_IM_MATERIALREQBILLPRICEINFO
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    int insert(MaterialReqBillPriceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_IM_MATERIALREQBILLPRICEINFO
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    int insertSelective(MaterialReqBillPriceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_IM_MATERIALREQBILLPRICEINFO
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    int updateByPrimaryKeySelective(MaterialReqBillPriceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_IM_MATERIALREQBILLPRICEINFO
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    int updateByPrimaryKey(MaterialReqBillPriceInfo record);
}