package  com.tubaoapi.dao;

import  com.tubaoapi.model.MaterialReqBill;

public interface MaterialReqBillDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_IM_MATERIALREQBILL
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    int insert(MaterialReqBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_IM_MATERIALREQBILL
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    int insertSelective(MaterialReqBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_IM_MATERIALREQBILL
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    int updateByPrimaryKeySelective(MaterialReqBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_IM_MATERIALREQBILL
     *
     * @mbggenerated Wed Jun 06 09:30:55 CST 2018
     */
    int updateByPrimaryKey(MaterialReqBill record);
}