package com.tubaoapi.model;


import java.math.BigDecimal;
import java.util.Date;

public class ManufactureRecBillEntry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FSEQ
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private Long fseq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private Object fsourcebillid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLNUMBER
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private Object fsourcebillnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLENTRYID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private Object fsourcebillentryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLENTRYSEQ
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private Long fsourcebillentryseq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FASSCOEFFICIENT
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private BigDecimal fasscoefficient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FBASESTATUS
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private Long fbasestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FASSOCIATEQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private BigDecimal fassociateqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLTYPEID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String fsourcebilltypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FASSISTPROPERTYID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String fassistpropertyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FMATERIALID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String fmaterialid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FUNITID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String funitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FBASEUNITID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String fbaseunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FASSISTUNITID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String fassistunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FREASONCODEID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String freasoncodeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FSTORAGEORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String fstorageorgunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FCOMPANYORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String fcompanyorgunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FWAREHOUSEID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String fwarehouseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FLOCATIONID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String flocationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FSTOCKERID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String fstockerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FLOT
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private Object flot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private BigDecimal fqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FASSISTQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private BigDecimal fassistqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FBASEQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private BigDecimal fbaseqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FREVERSEQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private BigDecimal freverseqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FRETURNSQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private BigDecimal freturnsqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FPRICE
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private BigDecimal fprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FAMOUNT
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private BigDecimal famount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FUNITSTANDARDCOST
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private BigDecimal funitstandardcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FSTANDARDCOST
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private BigDecimal fstandardcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FUNITACTUALCOST
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private BigDecimal funitactualcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FACTUALCOST
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private BigDecimal factualcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FISPRESENT
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private Long fispresent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FPARENTID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String fparentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FMANUBILLENTRYID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private Object fmanubillentryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FMANUBILLID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private Object fmanubillid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FMFG
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private Date fmfg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FEXP
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private Date fexp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FREMARK
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private Object fremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FREVERSEBASEQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private BigDecimal freversebaseqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FRETURNBASEQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private BigDecimal freturnbaseqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FCOSTOBJECTID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String fcostobjectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FRECQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private BigDecimal frecqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FBASERECQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private BigDecimal fbaserecqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FMANUBILLNUMBER
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private Object fmanubillnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FTRACENO
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String ftraceno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FSALEORDERBILLID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String fsaleorderbillid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FSALEORDERNUM
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private Object fsaleordernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FRECEIVEQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private BigDecimal freceiveqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FMANUBILLENTRYSEQ
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private Long fmanubillentryseq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FSALEORDERENTRYSEQ
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private Long fsaleorderentryseq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FPROJECTID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String fprojectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FTRACKNUMBERID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String ftracknumberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FCUSTOMERID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String fcustomerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FSUPPLIERID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String fsupplierid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FBIZDATE
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private Date fbizdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FCOSTCENTERORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String fcostcenterorgunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILLENTRY.FADMINORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    private String fadminorgunitid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FID
     *
     * @param fid the value for T_IM_MANUFACTURERECBILLENTRY.FID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFid(String fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSEQ
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FSEQ
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public Long getFseq() {
        return fseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSEQ
     *
     * @param fseq the value for T_IM_MANUFACTURERECBILLENTRY.FSEQ
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFseq(Long fseq) {
        this.fseq = fseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public Object getFsourcebillid() {
        return fsourcebillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLID
     *
     * @param fsourcebillid the value for T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFsourcebillid(Object fsourcebillid) {
        this.fsourcebillid = fsourcebillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLNUMBER
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLNUMBER
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public Object getFsourcebillnumber() {
        return fsourcebillnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLNUMBER
     *
     * @param fsourcebillnumber the value for T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLNUMBER
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFsourcebillnumber(Object fsourcebillnumber) {
        this.fsourcebillnumber = fsourcebillnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLENTRYID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLENTRYID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public Object getFsourcebillentryid() {
        return fsourcebillentryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLENTRYID
     *
     * @param fsourcebillentryid the value for T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLENTRYID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFsourcebillentryid(Object fsourcebillentryid) {
        this.fsourcebillentryid = fsourcebillentryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLENTRYSEQ
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLENTRYSEQ
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public Long getFsourcebillentryseq() {
        return fsourcebillentryseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLENTRYSEQ
     *
     * @param fsourcebillentryseq the value for T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLENTRYSEQ
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFsourcebillentryseq(Long fsourcebillentryseq) {
        this.fsourcebillentryseq = fsourcebillentryseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FASSCOEFFICIENT
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FASSCOEFFICIENT
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public BigDecimal getFasscoefficient() {
        return fasscoefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FASSCOEFFICIENT
     *
     * @param fasscoefficient the value for T_IM_MANUFACTURERECBILLENTRY.FASSCOEFFICIENT
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFasscoefficient(BigDecimal fasscoefficient) {
        this.fasscoefficient = fasscoefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FBASESTATUS
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FBASESTATUS
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public Long getFbasestatus() {
        return fbasestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FBASESTATUS
     *
     * @param fbasestatus the value for T_IM_MANUFACTURERECBILLENTRY.FBASESTATUS
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFbasestatus(Long fbasestatus) {
        this.fbasestatus = fbasestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FASSOCIATEQTY
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FASSOCIATEQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public BigDecimal getFassociateqty() {
        return fassociateqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FASSOCIATEQTY
     *
     * @param fassociateqty the value for T_IM_MANUFACTURERECBILLENTRY.FASSOCIATEQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFassociateqty(BigDecimal fassociateqty) {
        this.fassociateqty = fassociateqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLTYPEID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLTYPEID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFsourcebilltypeid() {
        return fsourcebilltypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLTYPEID
     *
     * @param fsourcebilltypeid the value for T_IM_MANUFACTURERECBILLENTRY.FSOURCEBILLTYPEID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFsourcebilltypeid(String fsourcebilltypeid) {
        this.fsourcebilltypeid = fsourcebilltypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FASSISTPROPERTYID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FASSISTPROPERTYID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFassistpropertyid() {
        return fassistpropertyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FASSISTPROPERTYID
     *
     * @param fassistpropertyid the value for T_IM_MANUFACTURERECBILLENTRY.FASSISTPROPERTYID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFassistpropertyid(String fassistpropertyid) {
        this.fassistpropertyid = fassistpropertyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FMATERIALID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FMATERIALID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFmaterialid() {
        return fmaterialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FMATERIALID
     *
     * @param fmaterialid the value for T_IM_MANUFACTURERECBILLENTRY.FMATERIALID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFmaterialid(String fmaterialid) {
        this.fmaterialid = fmaterialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FUNITID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FUNITID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFunitid() {
        return funitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FUNITID
     *
     * @param funitid the value for T_IM_MANUFACTURERECBILLENTRY.FUNITID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFunitid(String funitid) {
        this.funitid = funitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FBASEUNITID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FBASEUNITID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFbaseunitid() {
        return fbaseunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FBASEUNITID
     *
     * @param fbaseunitid the value for T_IM_MANUFACTURERECBILLENTRY.FBASEUNITID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFbaseunitid(String fbaseunitid) {
        this.fbaseunitid = fbaseunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FASSISTUNITID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FASSISTUNITID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFassistunitid() {
        return fassistunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FASSISTUNITID
     *
     * @param fassistunitid the value for T_IM_MANUFACTURERECBILLENTRY.FASSISTUNITID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFassistunitid(String fassistunitid) {
        this.fassistunitid = fassistunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FREASONCODEID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FREASONCODEID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFreasoncodeid() {
        return freasoncodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FREASONCODEID
     *
     * @param freasoncodeid the value for T_IM_MANUFACTURERECBILLENTRY.FREASONCODEID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFreasoncodeid(String freasoncodeid) {
        this.freasoncodeid = freasoncodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSTORAGEORGUNITID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FSTORAGEORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFstorageorgunitid() {
        return fstorageorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSTORAGEORGUNITID
     *
     * @param fstorageorgunitid the value for T_IM_MANUFACTURERECBILLENTRY.FSTORAGEORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFstorageorgunitid(String fstorageorgunitid) {
        this.fstorageorgunitid = fstorageorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FCOMPANYORGUNITID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FCOMPANYORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFcompanyorgunitid() {
        return fcompanyorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FCOMPANYORGUNITID
     *
     * @param fcompanyorgunitid the value for T_IM_MANUFACTURERECBILLENTRY.FCOMPANYORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFcompanyorgunitid(String fcompanyorgunitid) {
        this.fcompanyorgunitid = fcompanyorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FWAREHOUSEID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FWAREHOUSEID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFwarehouseid() {
        return fwarehouseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FWAREHOUSEID
     *
     * @param fwarehouseid the value for T_IM_MANUFACTURERECBILLENTRY.FWAREHOUSEID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFwarehouseid(String fwarehouseid) {
        this.fwarehouseid = fwarehouseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FLOCATIONID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FLOCATIONID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFlocationid() {
        return flocationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FLOCATIONID
     *
     * @param flocationid the value for T_IM_MANUFACTURERECBILLENTRY.FLOCATIONID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFlocationid(String flocationid) {
        this.flocationid = flocationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSTOCKERID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FSTOCKERID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFstockerid() {
        return fstockerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSTOCKERID
     *
     * @param fstockerid the value for T_IM_MANUFACTURERECBILLENTRY.FSTOCKERID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFstockerid(String fstockerid) {
        this.fstockerid = fstockerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FLOT
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FLOT
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public Object getFlot() {
        return flot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FLOT
     *
     * @param flot the value for T_IM_MANUFACTURERECBILLENTRY.FLOT
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFlot(Object flot) {
        this.flot = flot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FQTY
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public BigDecimal getFqty() {
        return fqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FQTY
     *
     * @param fqty the value for T_IM_MANUFACTURERECBILLENTRY.FQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFqty(BigDecimal fqty) {
        this.fqty = fqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FASSISTQTY
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FASSISTQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public BigDecimal getFassistqty() {
        return fassistqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FASSISTQTY
     *
     * @param fassistqty the value for T_IM_MANUFACTURERECBILLENTRY.FASSISTQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFassistqty(BigDecimal fassistqty) {
        this.fassistqty = fassistqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FBASEQTY
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FBASEQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public BigDecimal getFbaseqty() {
        return fbaseqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FBASEQTY
     *
     * @param fbaseqty the value for T_IM_MANUFACTURERECBILLENTRY.FBASEQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFbaseqty(BigDecimal fbaseqty) {
        this.fbaseqty = fbaseqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FREVERSEQTY
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FREVERSEQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public BigDecimal getFreverseqty() {
        return freverseqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FREVERSEQTY
     *
     * @param freverseqty the value for T_IM_MANUFACTURERECBILLENTRY.FREVERSEQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFreverseqty(BigDecimal freverseqty) {
        this.freverseqty = freverseqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FRETURNSQTY
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FRETURNSQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public BigDecimal getFreturnsqty() {
        return freturnsqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FRETURNSQTY
     *
     * @param freturnsqty the value for T_IM_MANUFACTURERECBILLENTRY.FRETURNSQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFreturnsqty(BigDecimal freturnsqty) {
        this.freturnsqty = freturnsqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FPRICE
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FPRICE
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public BigDecimal getFprice() {
        return fprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FPRICE
     *
     * @param fprice the value for T_IM_MANUFACTURERECBILLENTRY.FPRICE
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFprice(BigDecimal fprice) {
        this.fprice = fprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FAMOUNT
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FAMOUNT
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public BigDecimal getFamount() {
        return famount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FAMOUNT
     *
     * @param famount the value for T_IM_MANUFACTURERECBILLENTRY.FAMOUNT
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFamount(BigDecimal famount) {
        this.famount = famount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FUNITSTANDARDCOST
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FUNITSTANDARDCOST
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public BigDecimal getFunitstandardcost() {
        return funitstandardcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FUNITSTANDARDCOST
     *
     * @param funitstandardcost the value for T_IM_MANUFACTURERECBILLENTRY.FUNITSTANDARDCOST
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFunitstandardcost(BigDecimal funitstandardcost) {
        this.funitstandardcost = funitstandardcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSTANDARDCOST
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FSTANDARDCOST
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public BigDecimal getFstandardcost() {
        return fstandardcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSTANDARDCOST
     *
     * @param fstandardcost the value for T_IM_MANUFACTURERECBILLENTRY.FSTANDARDCOST
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFstandardcost(BigDecimal fstandardcost) {
        this.fstandardcost = fstandardcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FUNITACTUALCOST
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FUNITACTUALCOST
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public BigDecimal getFunitactualcost() {
        return funitactualcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FUNITACTUALCOST
     *
     * @param funitactualcost the value for T_IM_MANUFACTURERECBILLENTRY.FUNITACTUALCOST
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFunitactualcost(BigDecimal funitactualcost) {
        this.funitactualcost = funitactualcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FACTUALCOST
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FACTUALCOST
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public BigDecimal getFactualcost() {
        return factualcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FACTUALCOST
     *
     * @param factualcost the value for T_IM_MANUFACTURERECBILLENTRY.FACTUALCOST
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFactualcost(BigDecimal factualcost) {
        this.factualcost = factualcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FISPRESENT
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FISPRESENT
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public Long getFispresent() {
        return fispresent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FISPRESENT
     *
     * @param fispresent the value for T_IM_MANUFACTURERECBILLENTRY.FISPRESENT
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFispresent(Long fispresent) {
        this.fispresent = fispresent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FPARENTID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FPARENTID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFparentid() {
        return fparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FPARENTID
     *
     * @param fparentid the value for T_IM_MANUFACTURERECBILLENTRY.FPARENTID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFparentid(String fparentid) {
        this.fparentid = fparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FMANUBILLENTRYID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FMANUBILLENTRYID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public Object getFmanubillentryid() {
        return fmanubillentryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FMANUBILLENTRYID
     *
     * @param fmanubillentryid the value for T_IM_MANUFACTURERECBILLENTRY.FMANUBILLENTRYID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFmanubillentryid(Object fmanubillentryid) {
        this.fmanubillentryid = fmanubillentryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FMANUBILLID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FMANUBILLID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public Object getFmanubillid() {
        return fmanubillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FMANUBILLID
     *
     * @param fmanubillid the value for T_IM_MANUFACTURERECBILLENTRY.FMANUBILLID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFmanubillid(Object fmanubillid) {
        this.fmanubillid = fmanubillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FMFG
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FMFG
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public Date getFmfg() {
        return fmfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FMFG
     *
     * @param fmfg the value for T_IM_MANUFACTURERECBILLENTRY.FMFG
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFmfg(Date fmfg) {
        this.fmfg = fmfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FEXP
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FEXP
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public Date getFexp() {
        return fexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FEXP
     *
     * @param fexp the value for T_IM_MANUFACTURERECBILLENTRY.FEXP
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFexp(Date fexp) {
        this.fexp = fexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FREMARK
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FREMARK
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public Object getFremark() {
        return fremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FREMARK
     *
     * @param fremark the value for T_IM_MANUFACTURERECBILLENTRY.FREMARK
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFremark(Object fremark) {
        this.fremark = fremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FREVERSEBASEQTY
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FREVERSEBASEQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public BigDecimal getFreversebaseqty() {
        return freversebaseqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FREVERSEBASEQTY
     *
     * @param freversebaseqty the value for T_IM_MANUFACTURERECBILLENTRY.FREVERSEBASEQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFreversebaseqty(BigDecimal freversebaseqty) {
        this.freversebaseqty = freversebaseqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FRETURNBASEQTY
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FRETURNBASEQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public BigDecimal getFreturnbaseqty() {
        return freturnbaseqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FRETURNBASEQTY
     *
     * @param freturnbaseqty the value for T_IM_MANUFACTURERECBILLENTRY.FRETURNBASEQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFreturnbaseqty(BigDecimal freturnbaseqty) {
        this.freturnbaseqty = freturnbaseqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FCOSTOBJECTID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FCOSTOBJECTID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFcostobjectid() {
        return fcostobjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FCOSTOBJECTID
     *
     * @param fcostobjectid the value for T_IM_MANUFACTURERECBILLENTRY.FCOSTOBJECTID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFcostobjectid(String fcostobjectid) {
        this.fcostobjectid = fcostobjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FRECQTY
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FRECQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public BigDecimal getFrecqty() {
        return frecqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FRECQTY
     *
     * @param frecqty the value for T_IM_MANUFACTURERECBILLENTRY.FRECQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFrecqty(BigDecimal frecqty) {
        this.frecqty = frecqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FBASERECQTY
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FBASERECQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public BigDecimal getFbaserecqty() {
        return fbaserecqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FBASERECQTY
     *
     * @param fbaserecqty the value for T_IM_MANUFACTURERECBILLENTRY.FBASERECQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFbaserecqty(BigDecimal fbaserecqty) {
        this.fbaserecqty = fbaserecqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FMANUBILLNUMBER
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FMANUBILLNUMBER
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public Object getFmanubillnumber() {
        return fmanubillnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FMANUBILLNUMBER
     *
     * @param fmanubillnumber the value for T_IM_MANUFACTURERECBILLENTRY.FMANUBILLNUMBER
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFmanubillnumber(Object fmanubillnumber) {
        this.fmanubillnumber = fmanubillnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FTRACENO
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FTRACENO
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFtraceno() {
        return ftraceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FTRACENO
     *
     * @param ftraceno the value for T_IM_MANUFACTURERECBILLENTRY.FTRACENO
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFtraceno(String ftraceno) {
        this.ftraceno = ftraceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSALEORDERBILLID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FSALEORDERBILLID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFsaleorderbillid() {
        return fsaleorderbillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSALEORDERBILLID
     *
     * @param fsaleorderbillid the value for T_IM_MANUFACTURERECBILLENTRY.FSALEORDERBILLID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFsaleorderbillid(String fsaleorderbillid) {
        this.fsaleorderbillid = fsaleorderbillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSALEORDERNUM
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FSALEORDERNUM
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public Object getFsaleordernum() {
        return fsaleordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSALEORDERNUM
     *
     * @param fsaleordernum the value for T_IM_MANUFACTURERECBILLENTRY.FSALEORDERNUM
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFsaleordernum(Object fsaleordernum) {
        this.fsaleordernum = fsaleordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FRECEIVEQTY
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FRECEIVEQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public BigDecimal getFreceiveqty() {
        return freceiveqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FRECEIVEQTY
     *
     * @param freceiveqty the value for T_IM_MANUFACTURERECBILLENTRY.FRECEIVEQTY
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFreceiveqty(BigDecimal freceiveqty) {
        this.freceiveqty = freceiveqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FMANUBILLENTRYSEQ
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FMANUBILLENTRYSEQ
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public Long getFmanubillentryseq() {
        return fmanubillentryseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FMANUBILLENTRYSEQ
     *
     * @param fmanubillentryseq the value for T_IM_MANUFACTURERECBILLENTRY.FMANUBILLENTRYSEQ
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFmanubillentryseq(Long fmanubillentryseq) {
        this.fmanubillentryseq = fmanubillentryseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSALEORDERENTRYSEQ
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FSALEORDERENTRYSEQ
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public Long getFsaleorderentryseq() {
        return fsaleorderentryseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSALEORDERENTRYSEQ
     *
     * @param fsaleorderentryseq the value for T_IM_MANUFACTURERECBILLENTRY.FSALEORDERENTRYSEQ
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFsaleorderentryseq(Long fsaleorderentryseq) {
        this.fsaleorderentryseq = fsaleorderentryseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FPROJECTID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FPROJECTID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFprojectid() {
        return fprojectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FPROJECTID
     *
     * @param fprojectid the value for T_IM_MANUFACTURERECBILLENTRY.FPROJECTID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFprojectid(String fprojectid) {
        this.fprojectid = fprojectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FTRACKNUMBERID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FTRACKNUMBERID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFtracknumberid() {
        return ftracknumberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FTRACKNUMBERID
     *
     * @param ftracknumberid the value for T_IM_MANUFACTURERECBILLENTRY.FTRACKNUMBERID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFtracknumberid(String ftracknumberid) {
        this.ftracknumberid = ftracknumberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FCUSTOMERID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FCUSTOMERID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFcustomerid() {
        return fcustomerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FCUSTOMERID
     *
     * @param fcustomerid the value for T_IM_MANUFACTURERECBILLENTRY.FCUSTOMERID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFcustomerid(String fcustomerid) {
        this.fcustomerid = fcustomerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSUPPLIERID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FSUPPLIERID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFsupplierid() {
        return fsupplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FSUPPLIERID
     *
     * @param fsupplierid the value for T_IM_MANUFACTURERECBILLENTRY.FSUPPLIERID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFsupplierid(String fsupplierid) {
        this.fsupplierid = fsupplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FBIZDATE
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FBIZDATE
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public Date getFbizdate() {
        return fbizdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FBIZDATE
     *
     * @param fbizdate the value for T_IM_MANUFACTURERECBILLENTRY.FBIZDATE
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFbizdate(Date fbizdate) {
        this.fbizdate = fbizdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FCOSTCENTERORGUNITID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FCOSTCENTERORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFcostcenterorgunitid() {
        return fcostcenterorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FCOSTCENTERORGUNITID
     *
     * @param fcostcenterorgunitid the value for T_IM_MANUFACTURERECBILLENTRY.FCOSTCENTERORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFcostcenterorgunitid(String fcostcenterorgunitid) {
        this.fcostcenterorgunitid = fcostcenterorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILLENTRY.FADMINORGUNITID
     *
     * @return the value of T_IM_MANUFACTURERECBILLENTRY.FADMINORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public String getFadminorgunitid() {
        return fadminorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILLENTRY.FADMINORGUNITID
     *
     * @param fadminorgunitid the value for T_IM_MANUFACTURERECBILLENTRY.FADMINORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:57:05 CST 2018
     */
    public void setFadminorgunitid(String fadminorgunitid) {
        this.fadminorgunitid = fadminorgunitid;
    }
}