package com.tubaoapi.model;


import java.math.BigDecimal;
import java.util.Date;

public class ManufactureRecBill implements java.io.Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private String fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FCREATORID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private String fcreatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FCREATETIME
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private Date fcreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FLASTUPDATEUSERID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private String flastupdateuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FLASTUPDATETIME
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private Date flastupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FCONTROLUNITID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private String fcontrolunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FNUMBER
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private Object fnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FBIZDATE
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private Date fbizdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FHANDLERID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private String fhandlerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FDESCRIPTION
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private Object fdescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FHASEFFECTED
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private Long fhaseffected;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FAUDITORID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private String fauditorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FSOURCEBILLID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private Object fsourcebillid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FSOURCEFUNCTION
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private Object fsourcefunction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FAUDITTIME
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private Date faudittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FBASESTATUS
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private Long fbasestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FBIZTYPEID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private String fbiztypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FSOURCEBILLTYPEID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private String fsourcebilltypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FBILLTYPEID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private String fbilltypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FYEAR
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private Long fyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FPERIOD
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private Long fperiod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FSTORAGEORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private String fstorageorgunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FADMINORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private String fadminorgunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FSTOCKERID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private String fstockerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FVOUCHERID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private String fvoucherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FTOTALQTY
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private BigDecimal ftotalqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FTOTALAMOUNT
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private BigDecimal ftotalamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FFIVOUCHERED
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private Long ffivouchered;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FTOTALSTANDARDCOST
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private BigDecimal ftotalstandardcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FTOTALACTUALCOST
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private BigDecimal ftotalactualcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FISREVERSED
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private Long fisreversed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FTRANSACTIONTYPEID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private String ftransactiontypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FISINITBILL
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private Long fisinitbill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FMODIFIERID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private String fmodifierid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FMODIFICATIONTIME
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private Date fmodificationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FCOSTCENTERORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private String fcostcenterorgunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FISBACKFLUSHSUCCEED
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private Long fisbackflushsucceed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FMONTH
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private Long fmonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FDAY
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private Long fday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MANUFACTURERECBILL.FPROCESSORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    private String fprocessorgunitid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FID
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FID
     *
     * @param fid the value for T_IM_MANUFACTURERECBILL.FID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFid(String fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FCREATORID
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FCREATORID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public String getFcreatorid() {
        return fcreatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FCREATORID
     *
     * @param fcreatorid the value for T_IM_MANUFACTURERECBILL.FCREATORID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFcreatorid(String fcreatorid) {
        this.fcreatorid = fcreatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FCREATETIME
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FCREATETIME
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public Date getFcreatetime() {
        return fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FCREATETIME
     *
     * @param fcreatetime the value for T_IM_MANUFACTURERECBILL.FCREATETIME
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFcreatetime(Date fcreatetime) {
        this.fcreatetime = fcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FLASTUPDATEUSERID
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FLASTUPDATEUSERID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public String getFlastupdateuserid() {
        return flastupdateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FLASTUPDATEUSERID
     *
     * @param flastupdateuserid the value for T_IM_MANUFACTURERECBILL.FLASTUPDATEUSERID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFlastupdateuserid(String flastupdateuserid) {
        this.flastupdateuserid = flastupdateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FLASTUPDATETIME
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FLASTUPDATETIME
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public Date getFlastupdatetime() {
        return flastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FLASTUPDATETIME
     *
     * @param flastupdatetime the value for T_IM_MANUFACTURERECBILL.FLASTUPDATETIME
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFlastupdatetime(Date flastupdatetime) {
        this.flastupdatetime = flastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FCONTROLUNITID
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FCONTROLUNITID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public String getFcontrolunitid() {
        return fcontrolunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FCONTROLUNITID
     *
     * @param fcontrolunitid the value for T_IM_MANUFACTURERECBILL.FCONTROLUNITID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFcontrolunitid(String fcontrolunitid) {
        this.fcontrolunitid = fcontrolunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FNUMBER
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FNUMBER
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public Object getFnumber() {
        return fnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FNUMBER
     *
     * @param fnumber the value for T_IM_MANUFACTURERECBILL.FNUMBER
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFnumber(Object fnumber) {
        this.fnumber = fnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FBIZDATE
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FBIZDATE
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public Date getFbizdate() {
        return fbizdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FBIZDATE
     *
     * @param fbizdate the value for T_IM_MANUFACTURERECBILL.FBIZDATE
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFbizdate(Date fbizdate) {
        this.fbizdate = fbizdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FHANDLERID
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FHANDLERID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public String getFhandlerid() {
        return fhandlerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FHANDLERID
     *
     * @param fhandlerid the value for T_IM_MANUFACTURERECBILL.FHANDLERID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFhandlerid(String fhandlerid) {
        this.fhandlerid = fhandlerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FDESCRIPTION
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FDESCRIPTION
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public Object getFdescription() {
        return fdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FDESCRIPTION
     *
     * @param fdescription the value for T_IM_MANUFACTURERECBILL.FDESCRIPTION
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFdescription(Object fdescription) {
        this.fdescription = fdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FHASEFFECTED
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FHASEFFECTED
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public Long getFhaseffected() {
        return fhaseffected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FHASEFFECTED
     *
     * @param fhaseffected the value for T_IM_MANUFACTURERECBILL.FHASEFFECTED
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFhaseffected(Long fhaseffected) {
        this.fhaseffected = fhaseffected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FAUDITORID
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FAUDITORID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public String getFauditorid() {
        return fauditorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FAUDITORID
     *
     * @param fauditorid the value for T_IM_MANUFACTURERECBILL.FAUDITORID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFauditorid(String fauditorid) {
        this.fauditorid = fauditorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FSOURCEBILLID
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FSOURCEBILLID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public Object getFsourcebillid() {
        return fsourcebillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FSOURCEBILLID
     *
     * @param fsourcebillid the value for T_IM_MANUFACTURERECBILL.FSOURCEBILLID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFsourcebillid(Object fsourcebillid) {
        this.fsourcebillid = fsourcebillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FSOURCEFUNCTION
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FSOURCEFUNCTION
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public Object getFsourcefunction() {
        return fsourcefunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FSOURCEFUNCTION
     *
     * @param fsourcefunction the value for T_IM_MANUFACTURERECBILL.FSOURCEFUNCTION
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFsourcefunction(Object fsourcefunction) {
        this.fsourcefunction = fsourcefunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FAUDITTIME
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FAUDITTIME
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public Date getFaudittime() {
        return faudittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FAUDITTIME
     *
     * @param faudittime the value for T_IM_MANUFACTURERECBILL.FAUDITTIME
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFaudittime(Date faudittime) {
        this.faudittime = faudittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FBASESTATUS
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FBASESTATUS
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public Long getFbasestatus() {
        return fbasestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FBASESTATUS
     *
     * @param fbasestatus the value for T_IM_MANUFACTURERECBILL.FBASESTATUS
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFbasestatus(Long fbasestatus) {
        this.fbasestatus = fbasestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FBIZTYPEID
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FBIZTYPEID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public String getFbiztypeid() {
        return fbiztypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FBIZTYPEID
     *
     * @param fbiztypeid the value for T_IM_MANUFACTURERECBILL.FBIZTYPEID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFbiztypeid(String fbiztypeid) {
        this.fbiztypeid = fbiztypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FSOURCEBILLTYPEID
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FSOURCEBILLTYPEID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public String getFsourcebilltypeid() {
        return fsourcebilltypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FSOURCEBILLTYPEID
     *
     * @param fsourcebilltypeid the value for T_IM_MANUFACTURERECBILL.FSOURCEBILLTYPEID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFsourcebilltypeid(String fsourcebilltypeid) {
        this.fsourcebilltypeid = fsourcebilltypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FBILLTYPEID
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FBILLTYPEID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public String getFbilltypeid() {
        return fbilltypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FBILLTYPEID
     *
     * @param fbilltypeid the value for T_IM_MANUFACTURERECBILL.FBILLTYPEID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFbilltypeid(String fbilltypeid) {
        this.fbilltypeid = fbilltypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FYEAR
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FYEAR
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public Long getFyear() {
        return fyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FYEAR
     *
     * @param fyear the value for T_IM_MANUFACTURERECBILL.FYEAR
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFyear(Long fyear) {
        this.fyear = fyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FPERIOD
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FPERIOD
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public Long getFperiod() {
        return fperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FPERIOD
     *
     * @param fperiod the value for T_IM_MANUFACTURERECBILL.FPERIOD
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFperiod(Long fperiod) {
        this.fperiod = fperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FSTORAGEORGUNITID
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FSTORAGEORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public String getFstorageorgunitid() {
        return fstorageorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FSTORAGEORGUNITID
     *
     * @param fstorageorgunitid the value for T_IM_MANUFACTURERECBILL.FSTORAGEORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFstorageorgunitid(String fstorageorgunitid) {
        this.fstorageorgunitid = fstorageorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FADMINORGUNITID
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FADMINORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public String getFadminorgunitid() {
        return fadminorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FADMINORGUNITID
     *
     * @param fadminorgunitid the value for T_IM_MANUFACTURERECBILL.FADMINORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFadminorgunitid(String fadminorgunitid) {
        this.fadminorgunitid = fadminorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FSTOCKERID
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FSTOCKERID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public String getFstockerid() {
        return fstockerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FSTOCKERID
     *
     * @param fstockerid the value for T_IM_MANUFACTURERECBILL.FSTOCKERID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFstockerid(String fstockerid) {
        this.fstockerid = fstockerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FVOUCHERID
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FVOUCHERID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public String getFvoucherid() {
        return fvoucherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FVOUCHERID
     *
     * @param fvoucherid the value for T_IM_MANUFACTURERECBILL.FVOUCHERID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFvoucherid(String fvoucherid) {
        this.fvoucherid = fvoucherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FTOTALQTY
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FTOTALQTY
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public BigDecimal getFtotalqty() {
        return ftotalqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FTOTALQTY
     *
     * @param ftotalqty the value for T_IM_MANUFACTURERECBILL.FTOTALQTY
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFtotalqty(BigDecimal ftotalqty) {
        this.ftotalqty = ftotalqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FTOTALAMOUNT
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FTOTALAMOUNT
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public BigDecimal getFtotalamount() {
        return ftotalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FTOTALAMOUNT
     *
     * @param ftotalamount the value for T_IM_MANUFACTURERECBILL.FTOTALAMOUNT
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFtotalamount(BigDecimal ftotalamount) {
        this.ftotalamount = ftotalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FFIVOUCHERED
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FFIVOUCHERED
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public Long getFfivouchered() {
        return ffivouchered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FFIVOUCHERED
     *
     * @param ffivouchered the value for T_IM_MANUFACTURERECBILL.FFIVOUCHERED
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFfivouchered(Long ffivouchered) {
        this.ffivouchered = ffivouchered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FTOTALSTANDARDCOST
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FTOTALSTANDARDCOST
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public BigDecimal getFtotalstandardcost() {
        return ftotalstandardcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FTOTALSTANDARDCOST
     *
     * @param ftotalstandardcost the value for T_IM_MANUFACTURERECBILL.FTOTALSTANDARDCOST
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFtotalstandardcost(BigDecimal ftotalstandardcost) {
        this.ftotalstandardcost = ftotalstandardcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FTOTALACTUALCOST
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FTOTALACTUALCOST
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public BigDecimal getFtotalactualcost() {
        return ftotalactualcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FTOTALACTUALCOST
     *
     * @param ftotalactualcost the value for T_IM_MANUFACTURERECBILL.FTOTALACTUALCOST
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFtotalactualcost(BigDecimal ftotalactualcost) {
        this.ftotalactualcost = ftotalactualcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FISREVERSED
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FISREVERSED
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public Long getFisreversed() {
        return fisreversed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FISREVERSED
     *
     * @param fisreversed the value for T_IM_MANUFACTURERECBILL.FISREVERSED
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFisreversed(Long fisreversed) {
        this.fisreversed = fisreversed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FTRANSACTIONTYPEID
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FTRANSACTIONTYPEID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public String getFtransactiontypeid() {
        return ftransactiontypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FTRANSACTIONTYPEID
     *
     * @param ftransactiontypeid the value for T_IM_MANUFACTURERECBILL.FTRANSACTIONTYPEID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFtransactiontypeid(String ftransactiontypeid) {
        this.ftransactiontypeid = ftransactiontypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FISINITBILL
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FISINITBILL
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public Long getFisinitbill() {
        return fisinitbill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FISINITBILL
     *
     * @param fisinitbill the value for T_IM_MANUFACTURERECBILL.FISINITBILL
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFisinitbill(Long fisinitbill) {
        this.fisinitbill = fisinitbill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FMODIFIERID
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FMODIFIERID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public String getFmodifierid() {
        return fmodifierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FMODIFIERID
     *
     * @param fmodifierid the value for T_IM_MANUFACTURERECBILL.FMODIFIERID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFmodifierid(String fmodifierid) {
        this.fmodifierid = fmodifierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FMODIFICATIONTIME
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FMODIFICATIONTIME
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public Date getFmodificationtime() {
        return fmodificationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FMODIFICATIONTIME
     *
     * @param fmodificationtime the value for T_IM_MANUFACTURERECBILL.FMODIFICATIONTIME
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFmodificationtime(Date fmodificationtime) {
        this.fmodificationtime = fmodificationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FCOSTCENTERORGUNITID
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FCOSTCENTERORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public String getFcostcenterorgunitid() {
        return fcostcenterorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FCOSTCENTERORGUNITID
     *
     * @param fcostcenterorgunitid the value for T_IM_MANUFACTURERECBILL.FCOSTCENTERORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFcostcenterorgunitid(String fcostcenterorgunitid) {
        this.fcostcenterorgunitid = fcostcenterorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FISBACKFLUSHSUCCEED
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FISBACKFLUSHSUCCEED
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public Long getFisbackflushsucceed() {
        return fisbackflushsucceed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FISBACKFLUSHSUCCEED
     *
     * @param fisbackflushsucceed the value for T_IM_MANUFACTURERECBILL.FISBACKFLUSHSUCCEED
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFisbackflushsucceed(Long fisbackflushsucceed) {
        this.fisbackflushsucceed = fisbackflushsucceed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FMONTH
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FMONTH
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public Long getFmonth() {
        return fmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FMONTH
     *
     * @param fmonth the value for T_IM_MANUFACTURERECBILL.FMONTH
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFmonth(Long fmonth) {
        this.fmonth = fmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FDAY
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FDAY
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public Long getFday() {
        return fday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FDAY
     *
     * @param fday the value for T_IM_MANUFACTURERECBILL.FDAY
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFday(Long fday) {
        this.fday = fday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MANUFACTURERECBILL.FPROCESSORGUNITID
     *
     * @return the value of T_IM_MANUFACTURERECBILL.FPROCESSORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public String getFprocessorgunitid() {
        return fprocessorgunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MANUFACTURERECBILL.FPROCESSORGUNITID
     *
     * @param fprocessorgunitid the value for T_IM_MANUFACTURERECBILL.FPROCESSORGUNITID
     *
     * @mbggenerated Fri Jun 08 08:54:46 CST 2018
     */
    public void setFprocessorgunitid(String fprocessorgunitid) {
        this.fprocessorgunitid = fprocessorgunitid;
    }
}