package com.tubaoapi.model;


import java.math.BigDecimal;

public class MaterialReqBillPriceInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private String fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FPARENTID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private String fparentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FPRICE
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private BigDecimal fprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FDISCOUNTTYPE
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private Long fdiscounttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FDISCOUNT
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private BigDecimal fdiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FREALPRICE
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private BigDecimal frealprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FTAXRATE
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private BigDecimal ftaxrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FTAXPRICE
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private BigDecimal ftaxprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FREALTAXPRICE
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private BigDecimal frealtaxprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FMATERIALID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private String fmaterialid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FASSISTPROPERTYID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private String fassistpropertyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FUNITID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private String funitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private Object fsourcebillid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLNUMBER
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private Object fsourcebillnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLENTRYID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private Object fsourcebillentryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLENTRYSEQ
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private Long fsourcebillentryseq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FASSCOEFFICIENT
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private BigDecimal fasscoefficient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FBASESTATUS
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private Long fbasestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FASSOCIATEQTY
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private BigDecimal fassociateqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLTYPEID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private String fsourcebilltypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FBASEUNITID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private String fbaseunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FASSISTUNITID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private String fassistunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FREMARK
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private Object fremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FREASONCODEID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private String freasoncodeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FSEQ
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private Long fseq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_IM_MATERIALREQBILLPRICEINFO.FMATERIALREQENTRYID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    private String fmaterialreqentryid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FID
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FID
     *
     * @param fid the value for T_IM_MATERIALREQBILLPRICEINFO.FID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFid(String fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FPARENTID
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FPARENTID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public String getFparentid() {
        return fparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FPARENTID
     *
     * @param fparentid the value for T_IM_MATERIALREQBILLPRICEINFO.FPARENTID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFparentid(String fparentid) {
        this.fparentid = fparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FPRICE
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FPRICE
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public BigDecimal getFprice() {
        return fprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FPRICE
     *
     * @param fprice the value for T_IM_MATERIALREQBILLPRICEINFO.FPRICE
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFprice(BigDecimal fprice) {
        this.fprice = fprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FDISCOUNTTYPE
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FDISCOUNTTYPE
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public Long getFdiscounttype() {
        return fdiscounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FDISCOUNTTYPE
     *
     * @param fdiscounttype the value for T_IM_MATERIALREQBILLPRICEINFO.FDISCOUNTTYPE
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFdiscounttype(Long fdiscounttype) {
        this.fdiscounttype = fdiscounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FDISCOUNT
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FDISCOUNT
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public BigDecimal getFdiscount() {
        return fdiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FDISCOUNT
     *
     * @param fdiscount the value for T_IM_MATERIALREQBILLPRICEINFO.FDISCOUNT
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFdiscount(BigDecimal fdiscount) {
        this.fdiscount = fdiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FREALPRICE
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FREALPRICE
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public BigDecimal getFrealprice() {
        return frealprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FREALPRICE
     *
     * @param frealprice the value for T_IM_MATERIALREQBILLPRICEINFO.FREALPRICE
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFrealprice(BigDecimal frealprice) {
        this.frealprice = frealprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FTAXRATE
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FTAXRATE
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public BigDecimal getFtaxrate() {
        return ftaxrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FTAXRATE
     *
     * @param ftaxrate the value for T_IM_MATERIALREQBILLPRICEINFO.FTAXRATE
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFtaxrate(BigDecimal ftaxrate) {
        this.ftaxrate = ftaxrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FTAXPRICE
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FTAXPRICE
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public BigDecimal getFtaxprice() {
        return ftaxprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FTAXPRICE
     *
     * @param ftaxprice the value for T_IM_MATERIALREQBILLPRICEINFO.FTAXPRICE
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFtaxprice(BigDecimal ftaxprice) {
        this.ftaxprice = ftaxprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FREALTAXPRICE
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FREALTAXPRICE
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public BigDecimal getFrealtaxprice() {
        return frealtaxprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FREALTAXPRICE
     *
     * @param frealtaxprice the value for T_IM_MATERIALREQBILLPRICEINFO.FREALTAXPRICE
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFrealtaxprice(BigDecimal frealtaxprice) {
        this.frealtaxprice = frealtaxprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FMATERIALID
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FMATERIALID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public String getFmaterialid() {
        return fmaterialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FMATERIALID
     *
     * @param fmaterialid the value for T_IM_MATERIALREQBILLPRICEINFO.FMATERIALID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFmaterialid(String fmaterialid) {
        this.fmaterialid = fmaterialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FASSISTPROPERTYID
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FASSISTPROPERTYID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public String getFassistpropertyid() {
        return fassistpropertyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FASSISTPROPERTYID
     *
     * @param fassistpropertyid the value for T_IM_MATERIALREQBILLPRICEINFO.FASSISTPROPERTYID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFassistpropertyid(String fassistpropertyid) {
        this.fassistpropertyid = fassistpropertyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FUNITID
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FUNITID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public String getFunitid() {
        return funitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FUNITID
     *
     * @param funitid the value for T_IM_MATERIALREQBILLPRICEINFO.FUNITID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFunitid(String funitid) {
        this.funitid = funitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLID
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public Object getFsourcebillid() {
        return fsourcebillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLID
     *
     * @param fsourcebillid the value for T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFsourcebillid(Object fsourcebillid) {
        this.fsourcebillid = fsourcebillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLNUMBER
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLNUMBER
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public Object getFsourcebillnumber() {
        return fsourcebillnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLNUMBER
     *
     * @param fsourcebillnumber the value for T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLNUMBER
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFsourcebillnumber(Object fsourcebillnumber) {
        this.fsourcebillnumber = fsourcebillnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLENTRYID
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLENTRYID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public Object getFsourcebillentryid() {
        return fsourcebillentryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLENTRYID
     *
     * @param fsourcebillentryid the value for T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLENTRYID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFsourcebillentryid(Object fsourcebillentryid) {
        this.fsourcebillentryid = fsourcebillentryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLENTRYSEQ
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLENTRYSEQ
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public Long getFsourcebillentryseq() {
        return fsourcebillentryseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLENTRYSEQ
     *
     * @param fsourcebillentryseq the value for T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLENTRYSEQ
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFsourcebillentryseq(Long fsourcebillentryseq) {
        this.fsourcebillentryseq = fsourcebillentryseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FASSCOEFFICIENT
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FASSCOEFFICIENT
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public BigDecimal getFasscoefficient() {
        return fasscoefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FASSCOEFFICIENT
     *
     * @param fasscoefficient the value for T_IM_MATERIALREQBILLPRICEINFO.FASSCOEFFICIENT
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFasscoefficient(BigDecimal fasscoefficient) {
        this.fasscoefficient = fasscoefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FBASESTATUS
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FBASESTATUS
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public Long getFbasestatus() {
        return fbasestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FBASESTATUS
     *
     * @param fbasestatus the value for T_IM_MATERIALREQBILLPRICEINFO.FBASESTATUS
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFbasestatus(Long fbasestatus) {
        this.fbasestatus = fbasestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FASSOCIATEQTY
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FASSOCIATEQTY
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public BigDecimal getFassociateqty() {
        return fassociateqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FASSOCIATEQTY
     *
     * @param fassociateqty the value for T_IM_MATERIALREQBILLPRICEINFO.FASSOCIATEQTY
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFassociateqty(BigDecimal fassociateqty) {
        this.fassociateqty = fassociateqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLTYPEID
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLTYPEID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public String getFsourcebilltypeid() {
        return fsourcebilltypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLTYPEID
     *
     * @param fsourcebilltypeid the value for T_IM_MATERIALREQBILLPRICEINFO.FSOURCEBILLTYPEID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFsourcebilltypeid(String fsourcebilltypeid) {
        this.fsourcebilltypeid = fsourcebilltypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FBASEUNITID
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FBASEUNITID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public String getFbaseunitid() {
        return fbaseunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FBASEUNITID
     *
     * @param fbaseunitid the value for T_IM_MATERIALREQBILLPRICEINFO.FBASEUNITID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFbaseunitid(String fbaseunitid) {
        this.fbaseunitid = fbaseunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FASSISTUNITID
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FASSISTUNITID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public String getFassistunitid() {
        return fassistunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FASSISTUNITID
     *
     * @param fassistunitid the value for T_IM_MATERIALREQBILLPRICEINFO.FASSISTUNITID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFassistunitid(String fassistunitid) {
        this.fassistunitid = fassistunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FREMARK
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FREMARK
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public Object getFremark() {
        return fremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FREMARK
     *
     * @param fremark the value for T_IM_MATERIALREQBILLPRICEINFO.FREMARK
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFremark(Object fremark) {
        this.fremark = fremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FREASONCODEID
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FREASONCODEID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public String getFreasoncodeid() {
        return freasoncodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FREASONCODEID
     *
     * @param freasoncodeid the value for T_IM_MATERIALREQBILLPRICEINFO.FREASONCODEID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFreasoncodeid(String freasoncodeid) {
        this.freasoncodeid = freasoncodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FSEQ
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FSEQ
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public Long getFseq() {
        return fseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FSEQ
     *
     * @param fseq the value for T_IM_MATERIALREQBILLPRICEINFO.FSEQ
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFseq(Long fseq) {
        this.fseq = fseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FMATERIALREQENTRYID
     *
     * @return the value of T_IM_MATERIALREQBILLPRICEINFO.FMATERIALREQENTRYID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public String getFmaterialreqentryid() {
        return fmaterialreqentryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_IM_MATERIALREQBILLPRICEINFO.FMATERIALREQENTRYID
     *
     * @param fmaterialreqentryid the value for T_IM_MATERIALREQBILLPRICEINFO.FMATERIALREQENTRYID
     *
     * @mbggenerated Fri Jun 08 08:53:55 CST 2018
     */
    public void setFmaterialreqentryid(String fmaterialreqentryid) {
        this.fmaterialreqentryid = fmaterialreqentryid;
    }
}